### ISSUE TITLE
Bei nicht kompilierbarem Test muss man nach Grün wechseln können

### ISSUE THREAD

**Issue by gianperrone** [ProPra16/programmierpraktikum-abschlussprojekt-team-america#2]
Ich zitiere mal aus der Aufgabenstellung:
Wenn man den ersten Test für eine Methode schreibt, existiert die Methode noch nicht. Folglich kann der Test nicht kompiliert werden

Ich kann keinen Test schreiben, der fehlschlägt und kompiliert, wenn die zu testende Methode noch nicht existiert. Das müsst ihr bitte noch nachbessern.

**Comment by mosta100** [comment]
Ist mit dem letzten commit (der von vor 3 Tagen) von breadstealer möglich gemacht worden.
